name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.19"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: |
          go get -v ./...
      - name: Unit tests
        run: |
          go test -v ./...
      - name: Build arm64 mac
        env:
          GOOS: darwin
          GOARCH: arm64
        run: |
          go build -o bin/tfc
