name: Release
on:
  workflow_dispatch: {}
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Output tag
        id: create_tag
        run: |
          tag=$(basename "${{ github.ref }}")
          echo "::set-output name=tag::$tag"
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          release_name: ${{ steps.create_tag.outputs.tag }}
          draft: true
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
          prerelease: false
      - name: Build artifacts
        run: |
          bash scripts/build/build_and_zip_all.sh

  upload_assets:
    needs:
      - release
    strategy:
      matrix:
        os: [windows, linux, darwin]
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./artifacts/${{ matrix.os }}-${{ matrix.arch }}.zip
          asset_name: ${{ matrix.os }}-${{ matrix.arch }}.zip
          asset_content_type: application/zip
